package com.myself.appdemo.db.entity;

import com.myself.mylibrary.db.DBEntity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "putao_wd_store_paiband".
 */
@Entity(nameInDb = "putao_wd_store_paiband")
public class PaibandDB extends DBEntity {

    @Id(autoincrement = true)
    private Long _id;
    private String cid;
    private String data_content;
    private String date;
    private String is_uploaded;

    @Generated
    public PaibandDB() {
    }

    public PaibandDB(Long _id) {
        this._id = _id;
    }

    @Generated
    public PaibandDB(Long _id, String cid, String data_content, String date, String is_uploaded) {
        this._id = _id;
        this.cid = cid;
        this.data_content = data_content;
        this.date = date;
        this.is_uploaded = is_uploaded;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getData_content() {
        return data_content;
    }

    public void setData_content(String data_content) {
        this.data_content = data_content;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getIs_uploaded() {
        return is_uploaded;
    }

    public void setIs_uploaded(String is_uploaded) {
        this.is_uploaded = is_uploaded;
    }

}
