package com.myself.appdemo.db.entity;

import com.myself.mylibrary.db.DBEntity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "putao_wd_province".
 */
@Entity(nameInDb = "putao_wd_province")
public class ProvinceDB extends DBEntity {

    @Id
    private String province_id;
    private String name;

    @Generated
    public ProvinceDB() {
    }

    public ProvinceDB(String province_id) {
        this.province_id = province_id;
    }

    @Generated
    public ProvinceDB(String province_id, String name) {
        this.province_id = province_id;
        this.name = name;
    }

    public String getProvince_id() {
        return province_id;
    }

    public void setProvince_id(String province_id) {
        this.province_id = province_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
