package com.myself.appdemo.db.entity;

import com.myself.mylibrary.db.DBEntity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "putao_wd_message".
 */
@Entity(nameInDb = "putao_wd_message")
public class PushMessageDB extends DBEntity {

    @Id(autoincrement = true)
    private Long push_id;
    private String admin_id;
    private Integer show_location;
    private Integer data_type;
    private String cid;
    private String uid;
    private Integer goods_appid;
    private Integer goods_id;
    private String goods_name;
    private String location_type;
    private String location_action;
    private String status;
    private Integer release_time;
    private String customParams;
    private String templateParam;
    private String templateContent;

    @Generated
    public PushMessageDB() {
    }

    public PushMessageDB(Long push_id) {
        this.push_id = push_id;
    }

    @Generated
    public PushMessageDB(Long push_id, String admin_id, Integer show_location, Integer data_type, String cid, String uid, Integer goods_appid, Integer goods_id, String goods_name, String location_type, String location_action, String status, Integer release_time, String customParams, String templateParam, String templateContent) {
        this.push_id = push_id;
        this.admin_id = admin_id;
        this.show_location = show_location;
        this.data_type = data_type;
        this.cid = cid;
        this.uid = uid;
        this.goods_appid = goods_appid;
        this.goods_id = goods_id;
        this.goods_name = goods_name;
        this.location_type = location_type;
        this.location_action = location_action;
        this.status = status;
        this.release_time = release_time;
        this.customParams = customParams;
        this.templateParam = templateParam;
        this.templateContent = templateContent;
    }

    public Long getPush_id() {
        return push_id;
    }

    public void setPush_id(Long push_id) {
        this.push_id = push_id;
    }

    public String getAdmin_id() {
        return admin_id;
    }

    public void setAdmin_id(String admin_id) {
        this.admin_id = admin_id;
    }

    public Integer getShow_location() {
        return show_location;
    }

    public void setShow_location(Integer show_location) {
        this.show_location = show_location;
    }

    public Integer getData_type() {
        return data_type;
    }

    public void setData_type(Integer data_type) {
        this.data_type = data_type;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public Integer getGoods_appid() {
        return goods_appid;
    }

    public void setGoods_appid(Integer goods_appid) {
        this.goods_appid = goods_appid;
    }

    public Integer getGoods_id() {
        return goods_id;
    }

    public void setGoods_id(Integer goods_id) {
        this.goods_id = goods_id;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getLocation_type() {
        return location_type;
    }

    public void setLocation_type(String location_type) {
        this.location_type = location_type;
    }

    public String getLocation_action() {
        return location_action;
    }

    public void setLocation_action(String location_action) {
        this.location_action = location_action;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getRelease_time() {
        return release_time;
    }

    public void setRelease_time(Integer release_time) {
        this.release_time = release_time;
    }

    public String getCustomParams() {
        return customParams;
    }

    public void setCustomParams(String customParams) {
        this.customParams = customParams;
    }

    public String getTemplateParam() {
        return templateParam;
    }

    public void setTemplateParam(String templateParam) {
        this.templateParam = templateParam;
    }

    public String getTemplateContent() {
        return templateContent;
    }

    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent;
    }

}
