package com.myself.appdemo.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.myself.appdemo.db.entity.DistrictDB;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "putao_wd_district".
*/
public class DistrictDBDao extends AbstractDao<DistrictDB, String> {

    public static final String TABLENAME = "putao_wd_district";

    /**
     * Properties of entity DistrictDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Province_id = new Property(0, String.class, "province_id", false, "PROVINCE_ID");
        public final static Property City_id = new Property(1, String.class, "city_id", false, "CITY_ID");
        public final static Property District_id = new Property(2, String.class, "district_id", true, "DISTRICT_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
    }


    public DistrictDBDao(DaoConfig config) {
        super(config);
    }
    
    public DistrictDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"putao_wd_district\" (" + //
                "\"PROVINCE_ID\" TEXT," + // 0: province_id
                "\"CITY_ID\" TEXT," + // 1: city_id
                "\"DISTRICT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 2: district_id
                "\"NAME\" TEXT);"); // 3: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"putao_wd_district\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DistrictDB entity) {
        stmt.clearBindings();
 
        String province_id = entity.getProvince_id();
        if (province_id != null) {
            stmt.bindString(1, province_id);
        }
 
        String city_id = entity.getCity_id();
        if (city_id != null) {
            stmt.bindString(2, city_id);
        }
 
        String district_id = entity.getDistrict_id();
        if (district_id != null) {
            stmt.bindString(3, district_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DistrictDB entity) {
        stmt.clearBindings();
 
        String province_id = entity.getProvince_id();
        if (province_id != null) {
            stmt.bindString(1, province_id);
        }
 
        String city_id = entity.getCity_id();
        if (city_id != null) {
            stmt.bindString(2, city_id);
        }
 
        String district_id = entity.getDistrict_id();
        if (district_id != null) {
            stmt.bindString(3, district_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
    }    

    @Override
    public DistrictDB readEntity(Cursor cursor, int offset) {
        DistrictDB entity = new DistrictDB( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // province_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // city_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // district_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DistrictDB entity, int offset) {
        entity.setProvince_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCity_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDistrict_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DistrictDB entity, long rowId) {
        return entity.getDistrict_id();
    }
    
    @Override
    public String getKey(DistrictDB entity) {
        if(entity != null) {
            return entity.getDistrict_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DistrictDB entity) {
        return entity.getDistrict_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
